[package]
name = "faster-utf8-validator"
version = "0.1.0"
authors = ["Heinz N. Gies <heinz@licenser.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dev-dependencies]
proptest = "1.0"
criterion = "0.3"
mimalloc = "0.1"
core_affinity = "*"

[[bench]]
name = "criterion_bench"
harness = false